/**
 * Swift 2.0 simd swizzle extension library
 *
 * @author jarnoh@komplex.org
 *
*/

import simd

extension float2
{
	var xx:float2 { get { return float2(x,x); } }
	//var xy:float2 { get { return float2(x,y); } }
	var yx:float2 { get { return float2(y,x); } }
	var yy:float2 { get { return float2(y,y); } }
	var xxx:float3 { get { return float3(x,x,x); } }
	var xxy:float3 { get { return float3(x,x,y); } }
	var xyx:float3 { get { return float3(x,y,x); } }
	var xyy:float3 { get { return float3(x,y,y); } }
	var yxx:float3 { get { return float3(y,x,x); } }
	var yxy:float3 { get { return float3(y,x,y); } }
	var yyx:float3 { get { return float3(y,y,x); } }
	var yyy:float3 { get { return float3(y,y,y); } }
	var xxxx:float4 { get { return float4(x,x,x,x); } }
	var xxxy:float4 { get { return float4(x,x,x,y); } }
	var xxyx:float4 { get { return float4(x,x,y,x); } }
	var xxyy:float4 { get { return float4(x,x,y,y); } }
	var xyxx:float4 { get { return float4(x,y,x,x); } }
	var xyxy:float4 { get { return float4(x,y,x,y); } }
	var xyyx:float4 { get { return float4(x,y,y,x); } }
	var xyyy:float4 { get { return float4(x,y,y,y); } }
	var yxxx:float4 { get { return float4(y,x,x,x); } }
	var yxxy:float4 { get { return float4(y,x,x,y); } }
	var yxyx:float4 { get { return float4(y,x,y,x); } }
	var yxyy:float4 { get { return float4(y,x,y,y); } }
	var yyxx:float4 { get { return float4(y,y,x,x); } }
	var yyxy:float4 { get { return float4(y,y,x,y); } }
	var yyyx:float4 { get { return float4(y,y,y,x); } }
	var yyyy:float4 { get { return float4(y,y,y,y); } }
}

extension float3
{
	var xx:float2 { get { return float2(x,x); } }
	var xy:float2 { get { return float2(x,y); } }
	var xz:float2 { get { return float2(x,z); } }
	var yx:float2 { get { return float2(y,x); } }
	var yy:float2 { get { return float2(y,y); } }
	var yz:float2 { get { return float2(y,z); } }
	var zx:float2 { get { return float2(z,x); } }
	var zy:float2 { get { return float2(z,y); } }
	var zz:float2 { get { return float2(z,z); } }
	var xxx:float3 { get { return float3(x,x,x); } }
	var xxy:float3 { get { return float3(x,x,y); } }
	var xxz:float3 { get { return float3(x,x,z); } }
	var xyx:float3 { get { return float3(x,y,x); } }
	var xyy:float3 { get { return float3(x,y,y); } }
	//var xyz:float3 { get { return float3(x,y,z); } }
	var xzx:float3 { get { return float3(x,z,x); } }
	var xzy:float3 { get { return float3(x,z,y); } }
	var xzz:float3 { get { return float3(x,z,z); } }
	var yxx:float3 { get { return float3(y,x,x); } }
	var yxy:float3 { get { return float3(y,x,y); } }
	var yxz:float3 { get { return float3(y,x,z); } }
	var yyx:float3 { get { return float3(y,y,x); } }
	var yyy:float3 { get { return float3(y,y,y); } }
	var yyz:float3 { get { return float3(y,y,z); } }
	var yzx:float3 { get { return float3(y,z,x); } }
	var yzy:float3 { get { return float3(y,z,y); } }
	var yzz:float3 { get { return float3(y,z,z); } }
	var zxx:float3 { get { return float3(z,x,x); } }
	var zxy:float3 { get { return float3(z,x,y); } }
	var zxz:float3 { get { return float3(z,x,z); } }
	var zyx:float3 { get { return float3(z,y,x); } }
	var zyy:float3 { get { return float3(z,y,y); } }
	var zyz:float3 { get { return float3(z,y,z); } }
	var zzx:float3 { get { return float3(z,z,x); } }
	var zzy:float3 { get { return float3(z,z,y); } }
	var zzz:float3 { get { return float3(z,z,z); } }
	var xxxx:float4 { get { return float4(x,x,x,x); } }
	var xxxy:float4 { get { return float4(x,x,x,y); } }
	var xxxz:float4 { get { return float4(x,x,x,z); } }
	var xxyx:float4 { get { return float4(x,x,y,x); } }
	var xxyy:float4 { get { return float4(x,x,y,y); } }
	var xxyz:float4 { get { return float4(x,x,y,z); } }
	var xxzx:float4 { get { return float4(x,x,z,x); } }
	var xxzy:float4 { get { return float4(x,x,z,y); } }
	var xxzz:float4 { get { return float4(x,x,z,z); } }
	var xyxx:float4 { get { return float4(x,y,x,x); } }
	var xyxy:float4 { get { return float4(x,y,x,y); } }
	var xyxz:float4 { get { return float4(x,y,x,z); } }
	var xyyx:float4 { get { return float4(x,y,y,x); } }
	var xyyy:float4 { get { return float4(x,y,y,y); } }
	var xyyz:float4 { get { return float4(x,y,y,z); } }
	var xyzx:float4 { get { return float4(x,y,z,x); } }
	var xyzy:float4 { get { return float4(x,y,z,y); } }
	var xyzz:float4 { get { return float4(x,y,z,z); } }
	var xzxx:float4 { get { return float4(x,z,x,x); } }
	var xzxy:float4 { get { return float4(x,z,x,y); } }
	var xzxz:float4 { get { return float4(x,z,x,z); } }
	var xzyx:float4 { get { return float4(x,z,y,x); } }
	var xzyy:float4 { get { return float4(x,z,y,y); } }
	var xzyz:float4 { get { return float4(x,z,y,z); } }
	var xzzx:float4 { get { return float4(x,z,z,x); } }
	var xzzy:float4 { get { return float4(x,z,z,y); } }
	var xzzz:float4 { get { return float4(x,z,z,z); } }
	var yxxx:float4 { get { return float4(y,x,x,x); } }
	var yxxy:float4 { get { return float4(y,x,x,y); } }
	var yxxz:float4 { get { return float4(y,x,x,z); } }
	var yxyx:float4 { get { return float4(y,x,y,x); } }
	var yxyy:float4 { get { return float4(y,x,y,y); } }
	var yxyz:float4 { get { return float4(y,x,y,z); } }
	var yxzx:float4 { get { return float4(y,x,z,x); } }
	var yxzy:float4 { get { return float4(y,x,z,y); } }
	var yxzz:float4 { get { return float4(y,x,z,z); } }
	var yyxx:float4 { get { return float4(y,y,x,x); } }
	var yyxy:float4 { get { return float4(y,y,x,y); } }
	var yyxz:float4 { get { return float4(y,y,x,z); } }
	var yyyx:float4 { get { return float4(y,y,y,x); } }
	var yyyy:float4 { get { return float4(y,y,y,y); } }
	var yyyz:float4 { get { return float4(y,y,y,z); } }
	var yyzx:float4 { get { return float4(y,y,z,x); } }
	var yyzy:float4 { get { return float4(y,y,z,y); } }
	var yyzz:float4 { get { return float4(y,y,z,z); } }
	var yzxx:float4 { get { return float4(y,z,x,x); } }
	var yzxy:float4 { get { return float4(y,z,x,y); } }
	var yzxz:float4 { get { return float4(y,z,x,z); } }
	var yzyx:float4 { get { return float4(y,z,y,x); } }
	var yzyy:float4 { get { return float4(y,z,y,y); } }
	var yzyz:float4 { get { return float4(y,z,y,z); } }
	var yzzx:float4 { get { return float4(y,z,z,x); } }
	var yzzy:float4 { get { return float4(y,z,z,y); } }
	var yzzz:float4 { get { return float4(y,z,z,z); } }
	var zxxx:float4 { get { return float4(z,x,x,x); } }
	var zxxy:float4 { get { return float4(z,x,x,y); } }
	var zxxz:float4 { get { return float4(z,x,x,z); } }
	var zxyx:float4 { get { return float4(z,x,y,x); } }
	var zxyy:float4 { get { return float4(z,x,y,y); } }
	var zxyz:float4 { get { return float4(z,x,y,z); } }
	var zxzx:float4 { get { return float4(z,x,z,x); } }
	var zxzy:float4 { get { return float4(z,x,z,y); } }
	var zxzz:float4 { get { return float4(z,x,z,z); } }
	var zyxx:float4 { get { return float4(z,y,x,x); } }
	var zyxy:float4 { get { return float4(z,y,x,y); } }
	var zyxz:float4 { get { return float4(z,y,x,z); } }
	var zyyx:float4 { get { return float4(z,y,y,x); } }
	var zyyy:float4 { get { return float4(z,y,y,y); } }
	var zyyz:float4 { get { return float4(z,y,y,z); } }
	var zyzx:float4 { get { return float4(z,y,z,x); } }
	var zyzy:float4 { get { return float4(z,y,z,y); } }
	var zyzz:float4 { get { return float4(z,y,z,z); } }
	var zzxx:float4 { get { return float4(z,z,x,x); } }
	var zzxy:float4 { get { return float4(z,z,x,y); } }
	var zzxz:float4 { get { return float4(z,z,x,z); } }
	var zzyx:float4 { get { return float4(z,z,y,x); } }
	var zzyy:float4 { get { return float4(z,z,y,y); } }
	var zzyz:float4 { get { return float4(z,z,y,z); } }
	var zzzx:float4 { get { return float4(z,z,z,x); } }
	var zzzy:float4 { get { return float4(z,z,z,y); } }
	var zzzz:float4 { get { return float4(z,z,z,z); } }
}

extension float4
{
	var xx:float2 { get { return float2(x,x); } }
	var xy:float2 { get { return float2(x,y); } }
	var xz:float2 { get { return float2(x,z); } }
	var xw:float2 { get { return float2(x,w); } }
	var yx:float2 { get { return float2(y,x); } }
	var yy:float2 { get { return float2(y,y); } }
	var yz:float2 { get { return float2(y,z); } }
	var yw:float2 { get { return float2(y,w); } }
	var zx:float2 { get { return float2(z,x); } }
	var zy:float2 { get { return float2(z,y); } }
	var zz:float2 { get { return float2(z,z); } }
	var zw:float2 { get { return float2(z,w); } }
	var wx:float2 { get { return float2(w,x); } }
	var wy:float2 { get { return float2(w,y); } }
	var wz:float2 { get { return float2(w,z); } }
	var ww:float2 { get { return float2(w,w); } }
	var xxx:float3 { get { return float3(x,x,x); } }
	var xxy:float3 { get { return float3(x,x,y); } }
	var xxz:float3 { get { return float3(x,x,z); } }
	var xxw:float3 { get { return float3(x,x,w); } }
	var xyx:float3 { get { return float3(x,y,x); } }
	var xyy:float3 { get { return float3(x,y,y); } }
	var xyz:float3 { get { return float3(x,y,z); } }
	var xyw:float3 { get { return float3(x,y,w); } }
	var xzx:float3 { get { return float3(x,z,x); } }
	var xzy:float3 { get { return float3(x,z,y); } }
	var xzz:float3 { get { return float3(x,z,z); } }
	var xzw:float3 { get { return float3(x,z,w); } }
	var xwx:float3 { get { return float3(x,w,x); } }
	var xwy:float3 { get { return float3(x,w,y); } }
	var xwz:float3 { get { return float3(x,w,z); } }
	var xww:float3 { get { return float3(x,w,w); } }
	var yxx:float3 { get { return float3(y,x,x); } }
	var yxy:float3 { get { return float3(y,x,y); } }
	var yxz:float3 { get { return float3(y,x,z); } }
	var yxw:float3 { get { return float3(y,x,w); } }
	var yyx:float3 { get { return float3(y,y,x); } }
	var yyy:float3 { get { return float3(y,y,y); } }
	var yyz:float3 { get { return float3(y,y,z); } }
	var yyw:float3 { get { return float3(y,y,w); } }
	var yzx:float3 { get { return float3(y,z,x); } }
	var yzy:float3 { get { return float3(y,z,y); } }
	var yzz:float3 { get { return float3(y,z,z); } }
	var yzw:float3 { get { return float3(y,z,w); } }
	var ywx:float3 { get { return float3(y,w,x); } }
	var ywy:float3 { get { return float3(y,w,y); } }
	var ywz:float3 { get { return float3(y,w,z); } }
	var yww:float3 { get { return float3(y,w,w); } }
	var zxx:float3 { get { return float3(z,x,x); } }
	var zxy:float3 { get { return float3(z,x,y); } }
	var zxz:float3 { get { return float3(z,x,z); } }
	var zxw:float3 { get { return float3(z,x,w); } }
	var zyx:float3 { get { return float3(z,y,x); } }
	var zyy:float3 { get { return float3(z,y,y); } }
	var zyz:float3 { get { return float3(z,y,z); } }
	var zyw:float3 { get { return float3(z,y,w); } }
	var zzx:float3 { get { return float3(z,z,x); } }
	var zzy:float3 { get { return float3(z,z,y); } }
	var zzz:float3 { get { return float3(z,z,z); } }
	var zzw:float3 { get { return float3(z,z,w); } }
	var zwx:float3 { get { return float3(z,w,x); } }
	var zwy:float3 { get { return float3(z,w,y); } }
	var zwz:float3 { get { return float3(z,w,z); } }
	var zww:float3 { get { return float3(z,w,w); } }
	var wxx:float3 { get { return float3(w,x,x); } }
	var wxy:float3 { get { return float3(w,x,y); } }
	var wxz:float3 { get { return float3(w,x,z); } }
	var wxw:float3 { get { return float3(w,x,w); } }
	var wyx:float3 { get { return float3(w,y,x); } }
	var wyy:float3 { get { return float3(w,y,y); } }
	var wyz:float3 { get { return float3(w,y,z); } }
	var wyw:float3 { get { return float3(w,y,w); } }
	var wzx:float3 { get { return float3(w,z,x); } }
	var wzy:float3 { get { return float3(w,z,y); } }
	var wzz:float3 { get { return float3(w,z,z); } }
	var wzw:float3 { get { return float3(w,z,w); } }
	var wwx:float3 { get { return float3(w,w,x); } }
	var wwy:float3 { get { return float3(w,w,y); } }
	var wwz:float3 { get { return float3(w,w,z); } }
	var www:float3 { get { return float3(w,w,w); } }
	var xxxx:float4 { get { return float4(x,x,x,x); } }
	var xxxy:float4 { get { return float4(x,x,x,y); } }
	var xxxz:float4 { get { return float4(x,x,x,z); } }
	var xxxw:float4 { get { return float4(x,x,x,w); } }
	var xxyx:float4 { get { return float4(x,x,y,x); } }
	var xxyy:float4 { get { return float4(x,x,y,y); } }
	var xxyz:float4 { get { return float4(x,x,y,z); } }
	var xxyw:float4 { get { return float4(x,x,y,w); } }
	var xxzx:float4 { get { return float4(x,x,z,x); } }
	var xxzy:float4 { get { return float4(x,x,z,y); } }
	var xxzz:float4 { get { return float4(x,x,z,z); } }
	var xxzw:float4 { get { return float4(x,x,z,w); } }
	var xxwx:float4 { get { return float4(x,x,w,x); } }
	var xxwy:float4 { get { return float4(x,x,w,y); } }
	var xxwz:float4 { get { return float4(x,x,w,z); } }
	var xxww:float4 { get { return float4(x,x,w,w); } }
	var xyxx:float4 { get { return float4(x,y,x,x); } }
	var xyxy:float4 { get { return float4(x,y,x,y); } }
	var xyxz:float4 { get { return float4(x,y,x,z); } }
	var xyxw:float4 { get { return float4(x,y,x,w); } }
	var xyyx:float4 { get { return float4(x,y,y,x); } }
	var xyyy:float4 { get { return float4(x,y,y,y); } }
	var xyyz:float4 { get { return float4(x,y,y,z); } }
	var xyyw:float4 { get { return float4(x,y,y,w); } }
	var xyzx:float4 { get { return float4(x,y,z,x); } }
	var xyzy:float4 { get { return float4(x,y,z,y); } }
	var xyzz:float4 { get { return float4(x,y,z,z); } }
	//var xyzw:float4 { get { return float4(x,y,z,w); } }
	var xywx:float4 { get { return float4(x,y,w,x); } }
	var xywy:float4 { get { return float4(x,y,w,y); } }
	var xywz:float4 { get { return float4(x,y,w,z); } }
	var xyww:float4 { get { return float4(x,y,w,w); } }
	var xzxx:float4 { get { return float4(x,z,x,x); } }
	var xzxy:float4 { get { return float4(x,z,x,y); } }
	var xzxz:float4 { get { return float4(x,z,x,z); } }
	var xzxw:float4 { get { return float4(x,z,x,w); } }
	var xzyx:float4 { get { return float4(x,z,y,x); } }
	var xzyy:float4 { get { return float4(x,z,y,y); } }
	var xzyz:float4 { get { return float4(x,z,y,z); } }
	var xzyw:float4 { get { return float4(x,z,y,w); } }
	var xzzx:float4 { get { return float4(x,z,z,x); } }
	var xzzy:float4 { get { return float4(x,z,z,y); } }
	var xzzz:float4 { get { return float4(x,z,z,z); } }
	var xzzw:float4 { get { return float4(x,z,z,w); } }
	var xzwx:float4 { get { return float4(x,z,w,x); } }
	var xzwy:float4 { get { return float4(x,z,w,y); } }
	var xzwz:float4 { get { return float4(x,z,w,z); } }
	var xzww:float4 { get { return float4(x,z,w,w); } }
	var xwxx:float4 { get { return float4(x,w,x,x); } }
	var xwxy:float4 { get { return float4(x,w,x,y); } }
	var xwxz:float4 { get { return float4(x,w,x,z); } }
	var xwxw:float4 { get { return float4(x,w,x,w); } }
	var xwyx:float4 { get { return float4(x,w,y,x); } }
	var xwyy:float4 { get { return float4(x,w,y,y); } }
	var xwyz:float4 { get { return float4(x,w,y,z); } }
	var xwyw:float4 { get { return float4(x,w,y,w); } }
	var xwzx:float4 { get { return float4(x,w,z,x); } }
	var xwzy:float4 { get { return float4(x,w,z,y); } }
	var xwzz:float4 { get { return float4(x,w,z,z); } }
	var xwzw:float4 { get { return float4(x,w,z,w); } }
	var xwwx:float4 { get { return float4(x,w,w,x); } }
	var xwwy:float4 { get { return float4(x,w,w,y); } }
	var xwwz:float4 { get { return float4(x,w,w,z); } }
	var xwww:float4 { get { return float4(x,w,w,w); } }
	var yxxx:float4 { get { return float4(y,x,x,x); } }
	var yxxy:float4 { get { return float4(y,x,x,y); } }
	var yxxz:float4 { get { return float4(y,x,x,z); } }
	var yxxw:float4 { get { return float4(y,x,x,w); } }
	var yxyx:float4 { get { return float4(y,x,y,x); } }
	var yxyy:float4 { get { return float4(y,x,y,y); } }
	var yxyz:float4 { get { return float4(y,x,y,z); } }
	var yxyw:float4 { get { return float4(y,x,y,w); } }
	var yxzx:float4 { get { return float4(y,x,z,x); } }
	var yxzy:float4 { get { return float4(y,x,z,y); } }
	var yxzz:float4 { get { return float4(y,x,z,z); } }
	var yxzw:float4 { get { return float4(y,x,z,w); } }
	var yxwx:float4 { get { return float4(y,x,w,x); } }
	var yxwy:float4 { get { return float4(y,x,w,y); } }
	var yxwz:float4 { get { return float4(y,x,w,z); } }
	var yxww:float4 { get { return float4(y,x,w,w); } }
	var yyxx:float4 { get { return float4(y,y,x,x); } }
	var yyxy:float4 { get { return float4(y,y,x,y); } }
	var yyxz:float4 { get { return float4(y,y,x,z); } }
	var yyxw:float4 { get { return float4(y,y,x,w); } }
	var yyyx:float4 { get { return float4(y,y,y,x); } }
	var yyyy:float4 { get { return float4(y,y,y,y); } }
	var yyyz:float4 { get { return float4(y,y,y,z); } }
	var yyyw:float4 { get { return float4(y,y,y,w); } }
	var yyzx:float4 { get { return float4(y,y,z,x); } }
	var yyzy:float4 { get { return float4(y,y,z,y); } }
	var yyzz:float4 { get { return float4(y,y,z,z); } }
	var yyzw:float4 { get { return float4(y,y,z,w); } }
	var yywx:float4 { get { return float4(y,y,w,x); } }
	var yywy:float4 { get { return float4(y,y,w,y); } }
	var yywz:float4 { get { return float4(y,y,w,z); } }
	var yyww:float4 { get { return float4(y,y,w,w); } }
	var yzxx:float4 { get { return float4(y,z,x,x); } }
	var yzxy:float4 { get { return float4(y,z,x,y); } }
	var yzxz:float4 { get { return float4(y,z,x,z); } }
	var yzxw:float4 { get { return float4(y,z,x,w); } }
	var yzyx:float4 { get { return float4(y,z,y,x); } }
	var yzyy:float4 { get { return float4(y,z,y,y); } }
	var yzyz:float4 { get { return float4(y,z,y,z); } }
	var yzyw:float4 { get { return float4(y,z,y,w); } }
	var yzzx:float4 { get { return float4(y,z,z,x); } }
	var yzzy:float4 { get { return float4(y,z,z,y); } }
	var yzzz:float4 { get { return float4(y,z,z,z); } }
	var yzzw:float4 { get { return float4(y,z,z,w); } }
	var yzwx:float4 { get { return float4(y,z,w,x); } }
	var yzwy:float4 { get { return float4(y,z,w,y); } }
	var yzwz:float4 { get { return float4(y,z,w,z); } }
	var yzww:float4 { get { return float4(y,z,w,w); } }
	var ywxx:float4 { get { return float4(y,w,x,x); } }
	var ywxy:float4 { get { return float4(y,w,x,y); } }
	var ywxz:float4 { get { return float4(y,w,x,z); } }
	var ywxw:float4 { get { return float4(y,w,x,w); } }
	var ywyx:float4 { get { return float4(y,w,y,x); } }
	var ywyy:float4 { get { return float4(y,w,y,y); } }
	var ywyz:float4 { get { return float4(y,w,y,z); } }
	var ywyw:float4 { get { return float4(y,w,y,w); } }
	var ywzx:float4 { get { return float4(y,w,z,x); } }
	var ywzy:float4 { get { return float4(y,w,z,y); } }
	var ywzz:float4 { get { return float4(y,w,z,z); } }
	var ywzw:float4 { get { return float4(y,w,z,w); } }
	var ywwx:float4 { get { return float4(y,w,w,x); } }
	var ywwy:float4 { get { return float4(y,w,w,y); } }
	var ywwz:float4 { get { return float4(y,w,w,z); } }
	var ywww:float4 { get { return float4(y,w,w,w); } }
	var zxxx:float4 { get { return float4(z,x,x,x); } }
	var zxxy:float4 { get { return float4(z,x,x,y); } }
	var zxxz:float4 { get { return float4(z,x,x,z); } }
	var zxxw:float4 { get { return float4(z,x,x,w); } }
	var zxyx:float4 { get { return float4(z,x,y,x); } }
	var zxyy:float4 { get { return float4(z,x,y,y); } }
	var zxyz:float4 { get { return float4(z,x,y,z); } }
	var zxyw:float4 { get { return float4(z,x,y,w); } }
	var zxzx:float4 { get { return float4(z,x,z,x); } }
	var zxzy:float4 { get { return float4(z,x,z,y); } }
	var zxzz:float4 { get { return float4(z,x,z,z); } }
	var zxzw:float4 { get { return float4(z,x,z,w); } }
	var zxwx:float4 { get { return float4(z,x,w,x); } }
	var zxwy:float4 { get { return float4(z,x,w,y); } }
	var zxwz:float4 { get { return float4(z,x,w,z); } }
	var zxww:float4 { get { return float4(z,x,w,w); } }
	var zyxx:float4 { get { return float4(z,y,x,x); } }
	var zyxy:float4 { get { return float4(z,y,x,y); } }
	var zyxz:float4 { get { return float4(z,y,x,z); } }
	var zyxw:float4 { get { return float4(z,y,x,w); } }
	var zyyx:float4 { get { return float4(z,y,y,x); } }
	var zyyy:float4 { get { return float4(z,y,y,y); } }
	var zyyz:float4 { get { return float4(z,y,y,z); } }
	var zyyw:float4 { get { return float4(z,y,y,w); } }
	var zyzx:float4 { get { return float4(z,y,z,x); } }
	var zyzy:float4 { get { return float4(z,y,z,y); } }
	var zyzz:float4 { get { return float4(z,y,z,z); } }
	var zyzw:float4 { get { return float4(z,y,z,w); } }
	var zywx:float4 { get { return float4(z,y,w,x); } }
	var zywy:float4 { get { return float4(z,y,w,y); } }
	var zywz:float4 { get { return float4(z,y,w,z); } }
	var zyww:float4 { get { return float4(z,y,w,w); } }
	var zzxx:float4 { get { return float4(z,z,x,x); } }
	var zzxy:float4 { get { return float4(z,z,x,y); } }
	var zzxz:float4 { get { return float4(z,z,x,z); } }
	var zzxw:float4 { get { return float4(z,z,x,w); } }
	var zzyx:float4 { get { return float4(z,z,y,x); } }
	var zzyy:float4 { get { return float4(z,z,y,y); } }
	var zzyz:float4 { get { return float4(z,z,y,z); } }
	var zzyw:float4 { get { return float4(z,z,y,w); } }
	var zzzx:float4 { get { return float4(z,z,z,x); } }
	var zzzy:float4 { get { return float4(z,z,z,y); } }
	var zzzz:float4 { get { return float4(z,z,z,z); } }
	var zzzw:float4 { get { return float4(z,z,z,w); } }
	var zzwx:float4 { get { return float4(z,z,w,x); } }
	var zzwy:float4 { get { return float4(z,z,w,y); } }
	var zzwz:float4 { get { return float4(z,z,w,z); } }
	var zzww:float4 { get { return float4(z,z,w,w); } }
	var zwxx:float4 { get { return float4(z,w,x,x); } }
	var zwxy:float4 { get { return float4(z,w,x,y); } }
	var zwxz:float4 { get { return float4(z,w,x,z); } }
	var zwxw:float4 { get { return float4(z,w,x,w); } }
	var zwyx:float4 { get { return float4(z,w,y,x); } }
	var zwyy:float4 { get { return float4(z,w,y,y); } }
	var zwyz:float4 { get { return float4(z,w,y,z); } }
	var zwyw:float4 { get { return float4(z,w,y,w); } }
	var zwzx:float4 { get { return float4(z,w,z,x); } }
	var zwzy:float4 { get { return float4(z,w,z,y); } }
	var zwzz:float4 { get { return float4(z,w,z,z); } }
	var zwzw:float4 { get { return float4(z,w,z,w); } }
	var zwwx:float4 { get { return float4(z,w,w,x); } }
	var zwwy:float4 { get { return float4(z,w,w,y); } }
	var zwwz:float4 { get { return float4(z,w,w,z); } }
	var zwww:float4 { get { return float4(z,w,w,w); } }
	var wxxx:float4 { get { return float4(w,x,x,x); } }
	var wxxy:float4 { get { return float4(w,x,x,y); } }
	var wxxz:float4 { get { return float4(w,x,x,z); } }
	var wxxw:float4 { get { return float4(w,x,x,w); } }
	var wxyx:float4 { get { return float4(w,x,y,x); } }
	var wxyy:float4 { get { return float4(w,x,y,y); } }
	var wxyz:float4 { get { return float4(w,x,y,z); } }
	var wxyw:float4 { get { return float4(w,x,y,w); } }
	var wxzx:float4 { get { return float4(w,x,z,x); } }
	var wxzy:float4 { get { return float4(w,x,z,y); } }
	var wxzz:float4 { get { return float4(w,x,z,z); } }
	var wxzw:float4 { get { return float4(w,x,z,w); } }
	var wxwx:float4 { get { return float4(w,x,w,x); } }
	var wxwy:float4 { get { return float4(w,x,w,y); } }
	var wxwz:float4 { get { return float4(w,x,w,z); } }
	var wxww:float4 { get { return float4(w,x,w,w); } }
	var wyxx:float4 { get { return float4(w,y,x,x); } }
	var wyxy:float4 { get { return float4(w,y,x,y); } }
	var wyxz:float4 { get { return float4(w,y,x,z); } }
	var wyxw:float4 { get { return float4(w,y,x,w); } }
	var wyyx:float4 { get { return float4(w,y,y,x); } }
	var wyyy:float4 { get { return float4(w,y,y,y); } }
	var wyyz:float4 { get { return float4(w,y,y,z); } }
	var wyyw:float4 { get { return float4(w,y,y,w); } }
	var wyzx:float4 { get { return float4(w,y,z,x); } }
	var wyzy:float4 { get { return float4(w,y,z,y); } }
	var wyzz:float4 { get { return float4(w,y,z,z); } }
	var wyzw:float4 { get { return float4(w,y,z,w); } }
	var wywx:float4 { get { return float4(w,y,w,x); } }
	var wywy:float4 { get { return float4(w,y,w,y); } }
	var wywz:float4 { get { return float4(w,y,w,z); } }
	var wyww:float4 { get { return float4(w,y,w,w); } }
	var wzxx:float4 { get { return float4(w,z,x,x); } }
	var wzxy:float4 { get { return float4(w,z,x,y); } }
	var wzxz:float4 { get { return float4(w,z,x,z); } }
	var wzxw:float4 { get { return float4(w,z,x,w); } }
	var wzyx:float4 { get { return float4(w,z,y,x); } }
	var wzyy:float4 { get { return float4(w,z,y,y); } }
	var wzyz:float4 { get { return float4(w,z,y,z); } }
	var wzyw:float4 { get { return float4(w,z,y,w); } }
	var wzzx:float4 { get { return float4(w,z,z,x); } }
	var wzzy:float4 { get { return float4(w,z,z,y); } }
	var wzzz:float4 { get { return float4(w,z,z,z); } }
	var wzzw:float4 { get { return float4(w,z,z,w); } }
	var wzwx:float4 { get { return float4(w,z,w,x); } }
	var wzwy:float4 { get { return float4(w,z,w,y); } }
	var wzwz:float4 { get { return float4(w,z,w,z); } }
	var wzww:float4 { get { return float4(w,z,w,w); } }
	var wwxx:float4 { get { return float4(w,w,x,x); } }
	var wwxy:float4 { get { return float4(w,w,x,y); } }
	var wwxz:float4 { get { return float4(w,w,x,z); } }
	var wwxw:float4 { get { return float4(w,w,x,w); } }
	var wwyx:float4 { get { return float4(w,w,y,x); } }
	var wwyy:float4 { get { return float4(w,w,y,y); } }
	var wwyz:float4 { get { return float4(w,w,y,z); } }
	var wwyw:float4 { get { return float4(w,w,y,w); } }
	var wwzx:float4 { get { return float4(w,w,z,x); } }
	var wwzy:float4 { get { return float4(w,w,z,y); } }
	var wwzz:float4 { get { return float4(w,w,z,z); } }
	var wwzw:float4 { get { return float4(w,w,z,w); } }
	var wwwx:float4 { get { return float4(w,w,w,x); } }
	var wwwy:float4 { get { return float4(w,w,w,y); } }
	var wwwz:float4 { get { return float4(w,w,w,z); } }
	var wwww:float4 { get { return float4(w,w,w,w); } }
}

extension double2
{
	var xx:double2 { get { return double2(x,x); } }
	//var xy:double2 { get { return double2(x,y); } }
	var yx:double2 { get { return double2(y,x); } }
	var yy:double2 { get { return double2(y,y); } }
	var xxx:double3 { get { return double3(x,x,x); } }
	var xxy:double3 { get { return double3(x,x,y); } }
	var xyx:double3 { get { return double3(x,y,x); } }
	var xyy:double3 { get { return double3(x,y,y); } }
	var yxx:double3 { get { return double3(y,x,x); } }
	var yxy:double3 { get { return double3(y,x,y); } }
	var yyx:double3 { get { return double3(y,y,x); } }
	var yyy:double3 { get { return double3(y,y,y); } }
	var xxxx:double4 { get { return double4(x,x,x,x); } }
	var xxxy:double4 { get { return double4(x,x,x,y); } }
	var xxyx:double4 { get { return double4(x,x,y,x); } }
	var xxyy:double4 { get { return double4(x,x,y,y); } }
	var xyxx:double4 { get { return double4(x,y,x,x); } }
	var xyxy:double4 { get { return double4(x,y,x,y); } }
	var xyyx:double4 { get { return double4(x,y,y,x); } }
	var xyyy:double4 { get { return double4(x,y,y,y); } }
	var yxxx:double4 { get { return double4(y,x,x,x); } }
	var yxxy:double4 { get { return double4(y,x,x,y); } }
	var yxyx:double4 { get { return double4(y,x,y,x); } }
	var yxyy:double4 { get { return double4(y,x,y,y); } }
	var yyxx:double4 { get { return double4(y,y,x,x); } }
	var yyxy:double4 { get { return double4(y,y,x,y); } }
	var yyyx:double4 { get { return double4(y,y,y,x); } }
	var yyyy:double4 { get { return double4(y,y,y,y); } }
}

extension double3
{
	var xx:double2 { get { return double2(x,x); } }
	var xy:double2 { get { return double2(x,y); } }
	var xz:double2 { get { return double2(x,z); } }
	var yx:double2 { get { return double2(y,x); } }
	var yy:double2 { get { return double2(y,y); } }
	var yz:double2 { get { return double2(y,z); } }
	var zx:double2 { get { return double2(z,x); } }
	var zy:double2 { get { return double2(z,y); } }
	var zz:double2 { get { return double2(z,z); } }
	var xxx:double3 { get { return double3(x,x,x); } }
	var xxy:double3 { get { return double3(x,x,y); } }
	var xxz:double3 { get { return double3(x,x,z); } }
	var xyx:double3 { get { return double3(x,y,x); } }
	var xyy:double3 { get { return double3(x,y,y); } }
	//var xyz:double3 { get { return double3(x,y,z); } }
	var xzx:double3 { get { return double3(x,z,x); } }
	var xzy:double3 { get { return double3(x,z,y); } }
	var xzz:double3 { get { return double3(x,z,z); } }
	var yxx:double3 { get { return double3(y,x,x); } }
	var yxy:double3 { get { return double3(y,x,y); } }
	var yxz:double3 { get { return double3(y,x,z); } }
	var yyx:double3 { get { return double3(y,y,x); } }
	var yyy:double3 { get { return double3(y,y,y); } }
	var yyz:double3 { get { return double3(y,y,z); } }
	var yzx:double3 { get { return double3(y,z,x); } }
	var yzy:double3 { get { return double3(y,z,y); } }
	var yzz:double3 { get { return double3(y,z,z); } }
	var zxx:double3 { get { return double3(z,x,x); } }
	var zxy:double3 { get { return double3(z,x,y); } }
	var zxz:double3 { get { return double3(z,x,z); } }
	var zyx:double3 { get { return double3(z,y,x); } }
	var zyy:double3 { get { return double3(z,y,y); } }
	var zyz:double3 { get { return double3(z,y,z); } }
	var zzx:double3 { get { return double3(z,z,x); } }
	var zzy:double3 { get { return double3(z,z,y); } }
	var zzz:double3 { get { return double3(z,z,z); } }
	var xxxx:double4 { get { return double4(x,x,x,x); } }
	var xxxy:double4 { get { return double4(x,x,x,y); } }
	var xxxz:double4 { get { return double4(x,x,x,z); } }
	var xxyx:double4 { get { return double4(x,x,y,x); } }
	var xxyy:double4 { get { return double4(x,x,y,y); } }
	var xxyz:double4 { get { return double4(x,x,y,z); } }
	var xxzx:double4 { get { return double4(x,x,z,x); } }
	var xxzy:double4 { get { return double4(x,x,z,y); } }
	var xxzz:double4 { get { return double4(x,x,z,z); } }
	var xyxx:double4 { get { return double4(x,y,x,x); } }
	var xyxy:double4 { get { return double4(x,y,x,y); } }
	var xyxz:double4 { get { return double4(x,y,x,z); } }
	var xyyx:double4 { get { return double4(x,y,y,x); } }
	var xyyy:double4 { get { return double4(x,y,y,y); } }
	var xyyz:double4 { get { return double4(x,y,y,z); } }
	var xyzx:double4 { get { return double4(x,y,z,x); } }
	var xyzy:double4 { get { return double4(x,y,z,y); } }
	var xyzz:double4 { get { return double4(x,y,z,z); } }
	var xzxx:double4 { get { return double4(x,z,x,x); } }
	var xzxy:double4 { get { return double4(x,z,x,y); } }
	var xzxz:double4 { get { return double4(x,z,x,z); } }
	var xzyx:double4 { get { return double4(x,z,y,x); } }
	var xzyy:double4 { get { return double4(x,z,y,y); } }
	var xzyz:double4 { get { return double4(x,z,y,z); } }
	var xzzx:double4 { get { return double4(x,z,z,x); } }
	var xzzy:double4 { get { return double4(x,z,z,y); } }
	var xzzz:double4 { get { return double4(x,z,z,z); } }
	var yxxx:double4 { get { return double4(y,x,x,x); } }
	var yxxy:double4 { get { return double4(y,x,x,y); } }
	var yxxz:double4 { get { return double4(y,x,x,z); } }
	var yxyx:double4 { get { return double4(y,x,y,x); } }
	var yxyy:double4 { get { return double4(y,x,y,y); } }
	var yxyz:double4 { get { return double4(y,x,y,z); } }
	var yxzx:double4 { get { return double4(y,x,z,x); } }
	var yxzy:double4 { get { return double4(y,x,z,y); } }
	var yxzz:double4 { get { return double4(y,x,z,z); } }
	var yyxx:double4 { get { return double4(y,y,x,x); } }
	var yyxy:double4 { get { return double4(y,y,x,y); } }
	var yyxz:double4 { get { return double4(y,y,x,z); } }
	var yyyx:double4 { get { return double4(y,y,y,x); } }
	var yyyy:double4 { get { return double4(y,y,y,y); } }
	var yyyz:double4 { get { return double4(y,y,y,z); } }
	var yyzx:double4 { get { return double4(y,y,z,x); } }
	var yyzy:double4 { get { return double4(y,y,z,y); } }
	var yyzz:double4 { get { return double4(y,y,z,z); } }
	var yzxx:double4 { get { return double4(y,z,x,x); } }
	var yzxy:double4 { get { return double4(y,z,x,y); } }
	var yzxz:double4 { get { return double4(y,z,x,z); } }
	var yzyx:double4 { get { return double4(y,z,y,x); } }
	var yzyy:double4 { get { return double4(y,z,y,y); } }
	var yzyz:double4 { get { return double4(y,z,y,z); } }
	var yzzx:double4 { get { return double4(y,z,z,x); } }
	var yzzy:double4 { get { return double4(y,z,z,y); } }
	var yzzz:double4 { get { return double4(y,z,z,z); } }
	var zxxx:double4 { get { return double4(z,x,x,x); } }
	var zxxy:double4 { get { return double4(z,x,x,y); } }
	var zxxz:double4 { get { return double4(z,x,x,z); } }
	var zxyx:double4 { get { return double4(z,x,y,x); } }
	var zxyy:double4 { get { return double4(z,x,y,y); } }
	var zxyz:double4 { get { return double4(z,x,y,z); } }
	var zxzx:double4 { get { return double4(z,x,z,x); } }
	var zxzy:double4 { get { return double4(z,x,z,y); } }
	var zxzz:double4 { get { return double4(z,x,z,z); } }
	var zyxx:double4 { get { return double4(z,y,x,x); } }
	var zyxy:double4 { get { return double4(z,y,x,y); } }
	var zyxz:double4 { get { return double4(z,y,x,z); } }
	var zyyx:double4 { get { return double4(z,y,y,x); } }
	var zyyy:double4 { get { return double4(z,y,y,y); } }
	var zyyz:double4 { get { return double4(z,y,y,z); } }
	var zyzx:double4 { get { return double4(z,y,z,x); } }
	var zyzy:double4 { get { return double4(z,y,z,y); } }
	var zyzz:double4 { get { return double4(z,y,z,z); } }
	var zzxx:double4 { get { return double4(z,z,x,x); } }
	var zzxy:double4 { get { return double4(z,z,x,y); } }
	var zzxz:double4 { get { return double4(z,z,x,z); } }
	var zzyx:double4 { get { return double4(z,z,y,x); } }
	var zzyy:double4 { get { return double4(z,z,y,y); } }
	var zzyz:double4 { get { return double4(z,z,y,z); } }
	var zzzx:double4 { get { return double4(z,z,z,x); } }
	var zzzy:double4 { get { return double4(z,z,z,y); } }
	var zzzz:double4 { get { return double4(z,z,z,z); } }
}

extension double4
{
	var xx:double2 { get { return double2(x,x); } }
	var xy:double2 { get { return double2(x,y); } }
	var xz:double2 { get { return double2(x,z); } }
	var xw:double2 { get { return double2(x,w); } }
	var yx:double2 { get { return double2(y,x); } }
	var yy:double2 { get { return double2(y,y); } }
	var yz:double2 { get { return double2(y,z); } }
	var yw:double2 { get { return double2(y,w); } }
	var zx:double2 { get { return double2(z,x); } }
	var zy:double2 { get { return double2(z,y); } }
	var zz:double2 { get { return double2(z,z); } }
	var zw:double2 { get { return double2(z,w); } }
	var wx:double2 { get { return double2(w,x); } }
	var wy:double2 { get { return double2(w,y); } }
	var wz:double2 { get { return double2(w,z); } }
	var ww:double2 { get { return double2(w,w); } }
	var xxx:double3 { get { return double3(x,x,x); } }
	var xxy:double3 { get { return double3(x,x,y); } }
	var xxz:double3 { get { return double3(x,x,z); } }
	var xxw:double3 { get { return double3(x,x,w); } }
	var xyx:double3 { get { return double3(x,y,x); } }
	var xyy:double3 { get { return double3(x,y,y); } }
	var xyz:double3 { get { return double3(x,y,z); } }
	var xyw:double3 { get { return double3(x,y,w); } }
	var xzx:double3 { get { return double3(x,z,x); } }
	var xzy:double3 { get { return double3(x,z,y); } }
	var xzz:double3 { get { return double3(x,z,z); } }
	var xzw:double3 { get { return double3(x,z,w); } }
	var xwx:double3 { get { return double3(x,w,x); } }
	var xwy:double3 { get { return double3(x,w,y); } }
	var xwz:double3 { get { return double3(x,w,z); } }
	var xww:double3 { get { return double3(x,w,w); } }
	var yxx:double3 { get { return double3(y,x,x); } }
	var yxy:double3 { get { return double3(y,x,y); } }
	var yxz:double3 { get { return double3(y,x,z); } }
	var yxw:double3 { get { return double3(y,x,w); } }
	var yyx:double3 { get { return double3(y,y,x); } }
	var yyy:double3 { get { return double3(y,y,y); } }
	var yyz:double3 { get { return double3(y,y,z); } }
	var yyw:double3 { get { return double3(y,y,w); } }
	var yzx:double3 { get { return double3(y,z,x); } }
	var yzy:double3 { get { return double3(y,z,y); } }
	var yzz:double3 { get { return double3(y,z,z); } }
	var yzw:double3 { get { return double3(y,z,w); } }
	var ywx:double3 { get { return double3(y,w,x); } }
	var ywy:double3 { get { return double3(y,w,y); } }
	var ywz:double3 { get { return double3(y,w,z); } }
	var yww:double3 { get { return double3(y,w,w); } }
	var zxx:double3 { get { return double3(z,x,x); } }
	var zxy:double3 { get { return double3(z,x,y); } }
	var zxz:double3 { get { return double3(z,x,z); } }
	var zxw:double3 { get { return double3(z,x,w); } }
	var zyx:double3 { get { return double3(z,y,x); } }
	var zyy:double3 { get { return double3(z,y,y); } }
	var zyz:double3 { get { return double3(z,y,z); } }
	var zyw:double3 { get { return double3(z,y,w); } }
	var zzx:double3 { get { return double3(z,z,x); } }
	var zzy:double3 { get { return double3(z,z,y); } }
	var zzz:double3 { get { return double3(z,z,z); } }
	var zzw:double3 { get { return double3(z,z,w); } }
	var zwx:double3 { get { return double3(z,w,x); } }
	var zwy:double3 { get { return double3(z,w,y); } }
	var zwz:double3 { get { return double3(z,w,z); } }
	var zww:double3 { get { return double3(z,w,w); } }
	var wxx:double3 { get { return double3(w,x,x); } }
	var wxy:double3 { get { return double3(w,x,y); } }
	var wxz:double3 { get { return double3(w,x,z); } }
	var wxw:double3 { get { return double3(w,x,w); } }
	var wyx:double3 { get { return double3(w,y,x); } }
	var wyy:double3 { get { return double3(w,y,y); } }
	var wyz:double3 { get { return double3(w,y,z); } }
	var wyw:double3 { get { return double3(w,y,w); } }
	var wzx:double3 { get { return double3(w,z,x); } }
	var wzy:double3 { get { return double3(w,z,y); } }
	var wzz:double3 { get { return double3(w,z,z); } }
	var wzw:double3 { get { return double3(w,z,w); } }
	var wwx:double3 { get { return double3(w,w,x); } }
	var wwy:double3 { get { return double3(w,w,y); } }
	var wwz:double3 { get { return double3(w,w,z); } }
	var www:double3 { get { return double3(w,w,w); } }
	var xxxx:double4 { get { return double4(x,x,x,x); } }
	var xxxy:double4 { get { return double4(x,x,x,y); } }
	var xxxz:double4 { get { return double4(x,x,x,z); } }
	var xxxw:double4 { get { return double4(x,x,x,w); } }
	var xxyx:double4 { get { return double4(x,x,y,x); } }
	var xxyy:double4 { get { return double4(x,x,y,y); } }
	var xxyz:double4 { get { return double4(x,x,y,z); } }
	var xxyw:double4 { get { return double4(x,x,y,w); } }
	var xxzx:double4 { get { return double4(x,x,z,x); } }
	var xxzy:double4 { get { return double4(x,x,z,y); } }
	var xxzz:double4 { get { return double4(x,x,z,z); } }
	var xxzw:double4 { get { return double4(x,x,z,w); } }
	var xxwx:double4 { get { return double4(x,x,w,x); } }
	var xxwy:double4 { get { return double4(x,x,w,y); } }
	var xxwz:double4 { get { return double4(x,x,w,z); } }
	var xxww:double4 { get { return double4(x,x,w,w); } }
	var xyxx:double4 { get { return double4(x,y,x,x); } }
	var xyxy:double4 { get { return double4(x,y,x,y); } }
	var xyxz:double4 { get { return double4(x,y,x,z); } }
	var xyxw:double4 { get { return double4(x,y,x,w); } }
	var xyyx:double4 { get { return double4(x,y,y,x); } }
	var xyyy:double4 { get { return double4(x,y,y,y); } }
	var xyyz:double4 { get { return double4(x,y,y,z); } }
	var xyyw:double4 { get { return double4(x,y,y,w); } }
	var xyzx:double4 { get { return double4(x,y,z,x); } }
	var xyzy:double4 { get { return double4(x,y,z,y); } }
	var xyzz:double4 { get { return double4(x,y,z,z); } }
	//var xyzw:double4 { get { return double4(x,y,z,w); } }
	var xywx:double4 { get { return double4(x,y,w,x); } }
	var xywy:double4 { get { return double4(x,y,w,y); } }
	var xywz:double4 { get { return double4(x,y,w,z); } }
	var xyww:double4 { get { return double4(x,y,w,w); } }
	var xzxx:double4 { get { return double4(x,z,x,x); } }
	var xzxy:double4 { get { return double4(x,z,x,y); } }
	var xzxz:double4 { get { return double4(x,z,x,z); } }
	var xzxw:double4 { get { return double4(x,z,x,w); } }
	var xzyx:double4 { get { return double4(x,z,y,x); } }
	var xzyy:double4 { get { return double4(x,z,y,y); } }
	var xzyz:double4 { get { return double4(x,z,y,z); } }
	var xzyw:double4 { get { return double4(x,z,y,w); } }
	var xzzx:double4 { get { return double4(x,z,z,x); } }
	var xzzy:double4 { get { return double4(x,z,z,y); } }
	var xzzz:double4 { get { return double4(x,z,z,z); } }
	var xzzw:double4 { get { return double4(x,z,z,w); } }
	var xzwx:double4 { get { return double4(x,z,w,x); } }
	var xzwy:double4 { get { return double4(x,z,w,y); } }
	var xzwz:double4 { get { return double4(x,z,w,z); } }
	var xzww:double4 { get { return double4(x,z,w,w); } }
	var xwxx:double4 { get { return double4(x,w,x,x); } }
	var xwxy:double4 { get { return double4(x,w,x,y); } }
	var xwxz:double4 { get { return double4(x,w,x,z); } }
	var xwxw:double4 { get { return double4(x,w,x,w); } }
	var xwyx:double4 { get { return double4(x,w,y,x); } }
	var xwyy:double4 { get { return double4(x,w,y,y); } }
	var xwyz:double4 { get { return double4(x,w,y,z); } }
	var xwyw:double4 { get { return double4(x,w,y,w); } }
	var xwzx:double4 { get { return double4(x,w,z,x); } }
	var xwzy:double4 { get { return double4(x,w,z,y); } }
	var xwzz:double4 { get { return double4(x,w,z,z); } }
	var xwzw:double4 { get { return double4(x,w,z,w); } }
	var xwwx:double4 { get { return double4(x,w,w,x); } }
	var xwwy:double4 { get { return double4(x,w,w,y); } }
	var xwwz:double4 { get { return double4(x,w,w,z); } }
	var xwww:double4 { get { return double4(x,w,w,w); } }
	var yxxx:double4 { get { return double4(y,x,x,x); } }
	var yxxy:double4 { get { return double4(y,x,x,y); } }
	var yxxz:double4 { get { return double4(y,x,x,z); } }
	var yxxw:double4 { get { return double4(y,x,x,w); } }
	var yxyx:double4 { get { return double4(y,x,y,x); } }
	var yxyy:double4 { get { return double4(y,x,y,y); } }
	var yxyz:double4 { get { return double4(y,x,y,z); } }
	var yxyw:double4 { get { return double4(y,x,y,w); } }
	var yxzx:double4 { get { return double4(y,x,z,x); } }
	var yxzy:double4 { get { return double4(y,x,z,y); } }
	var yxzz:double4 { get { return double4(y,x,z,z); } }
	var yxzw:double4 { get { return double4(y,x,z,w); } }
	var yxwx:double4 { get { return double4(y,x,w,x); } }
	var yxwy:double4 { get { return double4(y,x,w,y); } }
	var yxwz:double4 { get { return double4(y,x,w,z); } }
	var yxww:double4 { get { return double4(y,x,w,w); } }
	var yyxx:double4 { get { return double4(y,y,x,x); } }
	var yyxy:double4 { get { return double4(y,y,x,y); } }
	var yyxz:double4 { get { return double4(y,y,x,z); } }
	var yyxw:double4 { get { return double4(y,y,x,w); } }
	var yyyx:double4 { get { return double4(y,y,y,x); } }
	var yyyy:double4 { get { return double4(y,y,y,y); } }
	var yyyz:double4 { get { return double4(y,y,y,z); } }
	var yyyw:double4 { get { return double4(y,y,y,w); } }
	var yyzx:double4 { get { return double4(y,y,z,x); } }
	var yyzy:double4 { get { return double4(y,y,z,y); } }
	var yyzz:double4 { get { return double4(y,y,z,z); } }
	var yyzw:double4 { get { return double4(y,y,z,w); } }
	var yywx:double4 { get { return double4(y,y,w,x); } }
	var yywy:double4 { get { return double4(y,y,w,y); } }
	var yywz:double4 { get { return double4(y,y,w,z); } }
	var yyww:double4 { get { return double4(y,y,w,w); } }
	var yzxx:double4 { get { return double4(y,z,x,x); } }
	var yzxy:double4 { get { return double4(y,z,x,y); } }
	var yzxz:double4 { get { return double4(y,z,x,z); } }
	var yzxw:double4 { get { return double4(y,z,x,w); } }
	var yzyx:double4 { get { return double4(y,z,y,x); } }
	var yzyy:double4 { get { return double4(y,z,y,y); } }
	var yzyz:double4 { get { return double4(y,z,y,z); } }
	var yzyw:double4 { get { return double4(y,z,y,w); } }
	var yzzx:double4 { get { return double4(y,z,z,x); } }
	var yzzy:double4 { get { return double4(y,z,z,y); } }
	var yzzz:double4 { get { return double4(y,z,z,z); } }
	var yzzw:double4 { get { return double4(y,z,z,w); } }
	var yzwx:double4 { get { return double4(y,z,w,x); } }
	var yzwy:double4 { get { return double4(y,z,w,y); } }
	var yzwz:double4 { get { return double4(y,z,w,z); } }
	var yzww:double4 { get { return double4(y,z,w,w); } }
	var ywxx:double4 { get { return double4(y,w,x,x); } }
	var ywxy:double4 { get { return double4(y,w,x,y); } }
	var ywxz:double4 { get { return double4(y,w,x,z); } }
	var ywxw:double4 { get { return double4(y,w,x,w); } }
	var ywyx:double4 { get { return double4(y,w,y,x); } }
	var ywyy:double4 { get { return double4(y,w,y,y); } }
	var ywyz:double4 { get { return double4(y,w,y,z); } }
	var ywyw:double4 { get { return double4(y,w,y,w); } }
	var ywzx:double4 { get { return double4(y,w,z,x); } }
	var ywzy:double4 { get { return double4(y,w,z,y); } }
	var ywzz:double4 { get { return double4(y,w,z,z); } }
	var ywzw:double4 { get { return double4(y,w,z,w); } }
	var ywwx:double4 { get { return double4(y,w,w,x); } }
	var ywwy:double4 { get { return double4(y,w,w,y); } }
	var ywwz:double4 { get { return double4(y,w,w,z); } }
	var ywww:double4 { get { return double4(y,w,w,w); } }
	var zxxx:double4 { get { return double4(z,x,x,x); } }
	var zxxy:double4 { get { return double4(z,x,x,y); } }
	var zxxz:double4 { get { return double4(z,x,x,z); } }
	var zxxw:double4 { get { return double4(z,x,x,w); } }
	var zxyx:double4 { get { return double4(z,x,y,x); } }
	var zxyy:double4 { get { return double4(z,x,y,y); } }
	var zxyz:double4 { get { return double4(z,x,y,z); } }
	var zxyw:double4 { get { return double4(z,x,y,w); } }
	var zxzx:double4 { get { return double4(z,x,z,x); } }
	var zxzy:double4 { get { return double4(z,x,z,y); } }
	var zxzz:double4 { get { return double4(z,x,z,z); } }
	var zxzw:double4 { get { return double4(z,x,z,w); } }
	var zxwx:double4 { get { return double4(z,x,w,x); } }
	var zxwy:double4 { get { return double4(z,x,w,y); } }
	var zxwz:double4 { get { return double4(z,x,w,z); } }
	var zxww:double4 { get { return double4(z,x,w,w); } }
	var zyxx:double4 { get { return double4(z,y,x,x); } }
	var zyxy:double4 { get { return double4(z,y,x,y); } }
	var zyxz:double4 { get { return double4(z,y,x,z); } }
	var zyxw:double4 { get { return double4(z,y,x,w); } }
	var zyyx:double4 { get { return double4(z,y,y,x); } }
	var zyyy:double4 { get { return double4(z,y,y,y); } }
	var zyyz:double4 { get { return double4(z,y,y,z); } }
	var zyyw:double4 { get { return double4(z,y,y,w); } }
	var zyzx:double4 { get { return double4(z,y,z,x); } }
	var zyzy:double4 { get { return double4(z,y,z,y); } }
	var zyzz:double4 { get { return double4(z,y,z,z); } }
	var zyzw:double4 { get { return double4(z,y,z,w); } }
	var zywx:double4 { get { return double4(z,y,w,x); } }
	var zywy:double4 { get { return double4(z,y,w,y); } }
	var zywz:double4 { get { return double4(z,y,w,z); } }
	var zyww:double4 { get { return double4(z,y,w,w); } }
	var zzxx:double4 { get { return double4(z,z,x,x); } }
	var zzxy:double4 { get { return double4(z,z,x,y); } }
	var zzxz:double4 { get { return double4(z,z,x,z); } }
	var zzxw:double4 { get { return double4(z,z,x,w); } }
	var zzyx:double4 { get { return double4(z,z,y,x); } }
	var zzyy:double4 { get { return double4(z,z,y,y); } }
	var zzyz:double4 { get { return double4(z,z,y,z); } }
	var zzyw:double4 { get { return double4(z,z,y,w); } }
	var zzzx:double4 { get { return double4(z,z,z,x); } }
	var zzzy:double4 { get { return double4(z,z,z,y); } }
	var zzzz:double4 { get { return double4(z,z,z,z); } }
	var zzzw:double4 { get { return double4(z,z,z,w); } }
	var zzwx:double4 { get { return double4(z,z,w,x); } }
	var zzwy:double4 { get { return double4(z,z,w,y); } }
	var zzwz:double4 { get { return double4(z,z,w,z); } }
	var zzww:double4 { get { return double4(z,z,w,w); } }
	var zwxx:double4 { get { return double4(z,w,x,x); } }
	var zwxy:double4 { get { return double4(z,w,x,y); } }
	var zwxz:double4 { get { return double4(z,w,x,z); } }
	var zwxw:double4 { get { return double4(z,w,x,w); } }
	var zwyx:double4 { get { return double4(z,w,y,x); } }
	var zwyy:double4 { get { return double4(z,w,y,y); } }
	var zwyz:double4 { get { return double4(z,w,y,z); } }
	var zwyw:double4 { get { return double4(z,w,y,w); } }
	var zwzx:double4 { get { return double4(z,w,z,x); } }
	var zwzy:double4 { get { return double4(z,w,z,y); } }
	var zwzz:double4 { get { return double4(z,w,z,z); } }
	var zwzw:double4 { get { return double4(z,w,z,w); } }
	var zwwx:double4 { get { return double4(z,w,w,x); } }
	var zwwy:double4 { get { return double4(z,w,w,y); } }
	var zwwz:double4 { get { return double4(z,w,w,z); } }
	var zwww:double4 { get { return double4(z,w,w,w); } }
	var wxxx:double4 { get { return double4(w,x,x,x); } }
	var wxxy:double4 { get { return double4(w,x,x,y); } }
	var wxxz:double4 { get { return double4(w,x,x,z); } }
	var wxxw:double4 { get { return double4(w,x,x,w); } }
	var wxyx:double4 { get { return double4(w,x,y,x); } }
	var wxyy:double4 { get { return double4(w,x,y,y); } }
	var wxyz:double4 { get { return double4(w,x,y,z); } }
	var wxyw:double4 { get { return double4(w,x,y,w); } }
	var wxzx:double4 { get { return double4(w,x,z,x); } }
	var wxzy:double4 { get { return double4(w,x,z,y); } }
	var wxzz:double4 { get { return double4(w,x,z,z); } }
	var wxzw:double4 { get { return double4(w,x,z,w); } }
	var wxwx:double4 { get { return double4(w,x,w,x); } }
	var wxwy:double4 { get { return double4(w,x,w,y); } }
	var wxwz:double4 { get { return double4(w,x,w,z); } }
	var wxww:double4 { get { return double4(w,x,w,w); } }
	var wyxx:double4 { get { return double4(w,y,x,x); } }
	var wyxy:double4 { get { return double4(w,y,x,y); } }
	var wyxz:double4 { get { return double4(w,y,x,z); } }
	var wyxw:double4 { get { return double4(w,y,x,w); } }
	var wyyx:double4 { get { return double4(w,y,y,x); } }
	var wyyy:double4 { get { return double4(w,y,y,y); } }
	var wyyz:double4 { get { return double4(w,y,y,z); } }
	var wyyw:double4 { get { return double4(w,y,y,w); } }
	var wyzx:double4 { get { return double4(w,y,z,x); } }
	var wyzy:double4 { get { return double4(w,y,z,y); } }
	var wyzz:double4 { get { return double4(w,y,z,z); } }
	var wyzw:double4 { get { return double4(w,y,z,w); } }
	var wywx:double4 { get { return double4(w,y,w,x); } }
	var wywy:double4 { get { return double4(w,y,w,y); } }
	var wywz:double4 { get { return double4(w,y,w,z); } }
	var wyww:double4 { get { return double4(w,y,w,w); } }
	var wzxx:double4 { get { return double4(w,z,x,x); } }
	var wzxy:double4 { get { return double4(w,z,x,y); } }
	var wzxz:double4 { get { return double4(w,z,x,z); } }
	var wzxw:double4 { get { return double4(w,z,x,w); } }
	var wzyx:double4 { get { return double4(w,z,y,x); } }
	var wzyy:double4 { get { return double4(w,z,y,y); } }
	var wzyz:double4 { get { return double4(w,z,y,z); } }
	var wzyw:double4 { get { return double4(w,z,y,w); } }
	var wzzx:double4 { get { return double4(w,z,z,x); } }
	var wzzy:double4 { get { return double4(w,z,z,y); } }
	var wzzz:double4 { get { return double4(w,z,z,z); } }
	var wzzw:double4 { get { return double4(w,z,z,w); } }
	var wzwx:double4 { get { return double4(w,z,w,x); } }
	var wzwy:double4 { get { return double4(w,z,w,y); } }
	var wzwz:double4 { get { return double4(w,z,w,z); } }
	var wzww:double4 { get { return double4(w,z,w,w); } }
	var wwxx:double4 { get { return double4(w,w,x,x); } }
	var wwxy:double4 { get { return double4(w,w,x,y); } }
	var wwxz:double4 { get { return double4(w,w,x,z); } }
	var wwxw:double4 { get { return double4(w,w,x,w); } }
	var wwyx:double4 { get { return double4(w,w,y,x); } }
	var wwyy:double4 { get { return double4(w,w,y,y); } }
	var wwyz:double4 { get { return double4(w,w,y,z); } }
	var wwyw:double4 { get { return double4(w,w,y,w); } }
	var wwzx:double4 { get { return double4(w,w,z,x); } }
	var wwzy:double4 { get { return double4(w,w,z,y); } }
	var wwzz:double4 { get { return double4(w,w,z,z); } }
	var wwzw:double4 { get { return double4(w,w,z,w); } }
	var wwwx:double4 { get { return double4(w,w,w,x); } }
	var wwwy:double4 { get { return double4(w,w,w,y); } }
	var wwwz:double4 { get { return double4(w,w,w,z); } }
	var wwww:double4 { get { return double4(w,w,w,w); } }
}


extension int2
{
	var xx:int2 { get { return int2(x,x); } }
	//var xy:int2 { get { return int2(x,y); } }
	var yx:int2 { get { return int2(y,x); } }
	var yy:int2 { get { return int2(y,y); } }
	var xxx:int3 { get { return int3(x,x,x); } }
	var xxy:int3 { get { return int3(x,x,y); } }
	var xyx:int3 { get { return int3(x,y,x); } }
	var xyy:int3 { get { return int3(x,y,y); } }
	var yxx:int3 { get { return int3(y,x,x); } }
	var yxy:int3 { get { return int3(y,x,y); } }
	var yyx:int3 { get { return int3(y,y,x); } }
	var yyy:int3 { get { return int3(y,y,y); } }
	var xxxx:int4 { get { return int4(x,x,x,x); } }
	var xxxy:int4 { get { return int4(x,x,x,y); } }
	var xxyx:int4 { get { return int4(x,x,y,x); } }
	var xxyy:int4 { get { return int4(x,x,y,y); } }
	var xyxx:int4 { get { return int4(x,y,x,x); } }
	var xyxy:int4 { get { return int4(x,y,x,y); } }
	var xyyx:int4 { get { return int4(x,y,y,x); } }
	var xyyy:int4 { get { return int4(x,y,y,y); } }
	var yxxx:int4 { get { return int4(y,x,x,x); } }
	var yxxy:int4 { get { return int4(y,x,x,y); } }
	var yxyx:int4 { get { return int4(y,x,y,x); } }
	var yxyy:int4 { get { return int4(y,x,y,y); } }
	var yyxx:int4 { get { return int4(y,y,x,x); } }
	var yyxy:int4 { get { return int4(y,y,x,y); } }
	var yyyx:int4 { get { return int4(y,y,y,x); } }
	var yyyy:int4 { get { return int4(y,y,y,y); } }
}

extension int3
{
	var xx:int2 { get { return int2(x,x); } }
	var xy:int2 { get { return int2(x,y); } }
	var xz:int2 { get { return int2(x,z); } }
	var yx:int2 { get { return int2(y,x); } }
	var yy:int2 { get { return int2(y,y); } }
	var yz:int2 { get { return int2(y,z); } }
	var zx:int2 { get { return int2(z,x); } }
	var zy:int2 { get { return int2(z,y); } }
	var zz:int2 { get { return int2(z,z); } }
	var xxx:int3 { get { return int3(x,x,x); } }
	var xxy:int3 { get { return int3(x,x,y); } }
	var xxz:int3 { get { return int3(x,x,z); } }
	var xyx:int3 { get { return int3(x,y,x); } }
	var xyy:int3 { get { return int3(x,y,y); } }
	//var xyz:int3 { get { return int3(x,y,z); } }
	var xzx:int3 { get { return int3(x,z,x); } }
	var xzy:int3 { get { return int3(x,z,y); } }
	var xzz:int3 { get { return int3(x,z,z); } }
	var yxx:int3 { get { return int3(y,x,x); } }
	var yxy:int3 { get { return int3(y,x,y); } }
	var yxz:int3 { get { return int3(y,x,z); } }
	var yyx:int3 { get { return int3(y,y,x); } }
	var yyy:int3 { get { return int3(y,y,y); } }
	var yyz:int3 { get { return int3(y,y,z); } }
	var yzx:int3 { get { return int3(y,z,x); } }
	var yzy:int3 { get { return int3(y,z,y); } }
	var yzz:int3 { get { return int3(y,z,z); } }
	var zxx:int3 { get { return int3(z,x,x); } }
	var zxy:int3 { get { return int3(z,x,y); } }
	var zxz:int3 { get { return int3(z,x,z); } }
	var zyx:int3 { get { return int3(z,y,x); } }
	var zyy:int3 { get { return int3(z,y,y); } }
	var zyz:int3 { get { return int3(z,y,z); } }
	var zzx:int3 { get { return int3(z,z,x); } }
	var zzy:int3 { get { return int3(z,z,y); } }
	var zzz:int3 { get { return int3(z,z,z); } }
	var xxxx:int4 { get { return int4(x,x,x,x); } }
	var xxxy:int4 { get { return int4(x,x,x,y); } }
	var xxxz:int4 { get { return int4(x,x,x,z); } }
	var xxyx:int4 { get { return int4(x,x,y,x); } }
	var xxyy:int4 { get { return int4(x,x,y,y); } }
	var xxyz:int4 { get { return int4(x,x,y,z); } }
	var xxzx:int4 { get { return int4(x,x,z,x); } }
	var xxzy:int4 { get { return int4(x,x,z,y); } }
	var xxzz:int4 { get { return int4(x,x,z,z); } }
	var xyxx:int4 { get { return int4(x,y,x,x); } }
	var xyxy:int4 { get { return int4(x,y,x,y); } }
	var xyxz:int4 { get { return int4(x,y,x,z); } }
	var xyyx:int4 { get { return int4(x,y,y,x); } }
	var xyyy:int4 { get { return int4(x,y,y,y); } }
	var xyyz:int4 { get { return int4(x,y,y,z); } }
	var xyzx:int4 { get { return int4(x,y,z,x); } }
	var xyzy:int4 { get { return int4(x,y,z,y); } }
	var xyzz:int4 { get { return int4(x,y,z,z); } }
	var xzxx:int4 { get { return int4(x,z,x,x); } }
	var xzxy:int4 { get { return int4(x,z,x,y); } }
	var xzxz:int4 { get { return int4(x,z,x,z); } }
	var xzyx:int4 { get { return int4(x,z,y,x); } }
	var xzyy:int4 { get { return int4(x,z,y,y); } }
	var xzyz:int4 { get { return int4(x,z,y,z); } }
	var xzzx:int4 { get { return int4(x,z,z,x); } }
	var xzzy:int4 { get { return int4(x,z,z,y); } }
	var xzzz:int4 { get { return int4(x,z,z,z); } }
	var yxxx:int4 { get { return int4(y,x,x,x); } }
	var yxxy:int4 { get { return int4(y,x,x,y); } }
	var yxxz:int4 { get { return int4(y,x,x,z); } }
	var yxyx:int4 { get { return int4(y,x,y,x); } }
	var yxyy:int4 { get { return int4(y,x,y,y); } }
	var yxyz:int4 { get { return int4(y,x,y,z); } }
	var yxzx:int4 { get { return int4(y,x,z,x); } }
	var yxzy:int4 { get { return int4(y,x,z,y); } }
	var yxzz:int4 { get { return int4(y,x,z,z); } }
	var yyxx:int4 { get { return int4(y,y,x,x); } }
	var yyxy:int4 { get { return int4(y,y,x,y); } }
	var yyxz:int4 { get { return int4(y,y,x,z); } }
	var yyyx:int4 { get { return int4(y,y,y,x); } }
	var yyyy:int4 { get { return int4(y,y,y,y); } }
	var yyyz:int4 { get { return int4(y,y,y,z); } }
	var yyzx:int4 { get { return int4(y,y,z,x); } }
	var yyzy:int4 { get { return int4(y,y,z,y); } }
	var yyzz:int4 { get { return int4(y,y,z,z); } }
	var yzxx:int4 { get { return int4(y,z,x,x); } }
	var yzxy:int4 { get { return int4(y,z,x,y); } }
	var yzxz:int4 { get { return int4(y,z,x,z); } }
	var yzyx:int4 { get { return int4(y,z,y,x); } }
	var yzyy:int4 { get { return int4(y,z,y,y); } }
	var yzyz:int4 { get { return int4(y,z,y,z); } }
	var yzzx:int4 { get { return int4(y,z,z,x); } }
	var yzzy:int4 { get { return int4(y,z,z,y); } }
	var yzzz:int4 { get { return int4(y,z,z,z); } }
	var zxxx:int4 { get { return int4(z,x,x,x); } }
	var zxxy:int4 { get { return int4(z,x,x,y); } }
	var zxxz:int4 { get { return int4(z,x,x,z); } }
	var zxyx:int4 { get { return int4(z,x,y,x); } }
	var zxyy:int4 { get { return int4(z,x,y,y); } }
	var zxyz:int4 { get { return int4(z,x,y,z); } }
	var zxzx:int4 { get { return int4(z,x,z,x); } }
	var zxzy:int4 { get { return int4(z,x,z,y); } }
	var zxzz:int4 { get { return int4(z,x,z,z); } }
	var zyxx:int4 { get { return int4(z,y,x,x); } }
	var zyxy:int4 { get { return int4(z,y,x,y); } }
	var zyxz:int4 { get { return int4(z,y,x,z); } }
	var zyyx:int4 { get { return int4(z,y,y,x); } }
	var zyyy:int4 { get { return int4(z,y,y,y); } }
	var zyyz:int4 { get { return int4(z,y,y,z); } }
	var zyzx:int4 { get { return int4(z,y,z,x); } }
	var zyzy:int4 { get { return int4(z,y,z,y); } }
	var zyzz:int4 { get { return int4(z,y,z,z); } }
	var zzxx:int4 { get { return int4(z,z,x,x); } }
	var zzxy:int4 { get { return int4(z,z,x,y); } }
	var zzxz:int4 { get { return int4(z,z,x,z); } }
	var zzyx:int4 { get { return int4(z,z,y,x); } }
	var zzyy:int4 { get { return int4(z,z,y,y); } }
	var zzyz:int4 { get { return int4(z,z,y,z); } }
	var zzzx:int4 { get { return int4(z,z,z,x); } }
	var zzzy:int4 { get { return int4(z,z,z,y); } }
	var zzzz:int4 { get { return int4(z,z,z,z); } }
}

extension int4
{
	var xx:int2 { get { return int2(x,x); } }
	var xy:int2 { get { return int2(x,y); } }
	var xz:int2 { get { return int2(x,z); } }
	var xw:int2 { get { return int2(x,w); } }
	var yx:int2 { get { return int2(y,x); } }
	var yy:int2 { get { return int2(y,y); } }
	var yz:int2 { get { return int2(y,z); } }
	var yw:int2 { get { return int2(y,w); } }
	var zx:int2 { get { return int2(z,x); } }
	var zy:int2 { get { return int2(z,y); } }
	var zz:int2 { get { return int2(z,z); } }
	var zw:int2 { get { return int2(z,w); } }
	var wx:int2 { get { return int2(w,x); } }
	var wy:int2 { get { return int2(w,y); } }
	var wz:int2 { get { return int2(w,z); } }
	var ww:int2 { get { return int2(w,w); } }
	var xxx:int3 { get { return int3(x,x,x); } }
	var xxy:int3 { get { return int3(x,x,y); } }
	var xxz:int3 { get { return int3(x,x,z); } }
	var xxw:int3 { get { return int3(x,x,w); } }
	var xyx:int3 { get { return int3(x,y,x); } }
	var xyy:int3 { get { return int3(x,y,y); } }
	var xyz:int3 { get { return int3(x,y,z); } }
	var xyw:int3 { get { return int3(x,y,w); } }
	var xzx:int3 { get { return int3(x,z,x); } }
	var xzy:int3 { get { return int3(x,z,y); } }
	var xzz:int3 { get { return int3(x,z,z); } }
	var xzw:int3 { get { return int3(x,z,w); } }
	var xwx:int3 { get { return int3(x,w,x); } }
	var xwy:int3 { get { return int3(x,w,y); } }
	var xwz:int3 { get { return int3(x,w,z); } }
	var xww:int3 { get { return int3(x,w,w); } }
	var yxx:int3 { get { return int3(y,x,x); } }
	var yxy:int3 { get { return int3(y,x,y); } }
	var yxz:int3 { get { return int3(y,x,z); } }
	var yxw:int3 { get { return int3(y,x,w); } }
	var yyx:int3 { get { return int3(y,y,x); } }
	var yyy:int3 { get { return int3(y,y,y); } }
	var yyz:int3 { get { return int3(y,y,z); } }
	var yyw:int3 { get { return int3(y,y,w); } }
	var yzx:int3 { get { return int3(y,z,x); } }
	var yzy:int3 { get { return int3(y,z,y); } }
	var yzz:int3 { get { return int3(y,z,z); } }
	var yzw:int3 { get { return int3(y,z,w); } }
	var ywx:int3 { get { return int3(y,w,x); } }
	var ywy:int3 { get { return int3(y,w,y); } }
	var ywz:int3 { get { return int3(y,w,z); } }
	var yww:int3 { get { return int3(y,w,w); } }
	var zxx:int3 { get { return int3(z,x,x); } }
	var zxy:int3 { get { return int3(z,x,y); } }
	var zxz:int3 { get { return int3(z,x,z); } }
	var zxw:int3 { get { return int3(z,x,w); } }
	var zyx:int3 { get { return int3(z,y,x); } }
	var zyy:int3 { get { return int3(z,y,y); } }
	var zyz:int3 { get { return int3(z,y,z); } }
	var zyw:int3 { get { return int3(z,y,w); } }
	var zzx:int3 { get { return int3(z,z,x); } }
	var zzy:int3 { get { return int3(z,z,y); } }
	var zzz:int3 { get { return int3(z,z,z); } }
	var zzw:int3 { get { return int3(z,z,w); } }
	var zwx:int3 { get { return int3(z,w,x); } }
	var zwy:int3 { get { return int3(z,w,y); } }
	var zwz:int3 { get { return int3(z,w,z); } }
	var zww:int3 { get { return int3(z,w,w); } }
	var wxx:int3 { get { return int3(w,x,x); } }
	var wxy:int3 { get { return int3(w,x,y); } }
	var wxz:int3 { get { return int3(w,x,z); } }
	var wxw:int3 { get { return int3(w,x,w); } }
	var wyx:int3 { get { return int3(w,y,x); } }
	var wyy:int3 { get { return int3(w,y,y); } }
	var wyz:int3 { get { return int3(w,y,z); } }
	var wyw:int3 { get { return int3(w,y,w); } }
	var wzx:int3 { get { return int3(w,z,x); } }
	var wzy:int3 { get { return int3(w,z,y); } }
	var wzz:int3 { get { return int3(w,z,z); } }
	var wzw:int3 { get { return int3(w,z,w); } }
	var wwx:int3 { get { return int3(w,w,x); } }
	var wwy:int3 { get { return int3(w,w,y); } }
	var wwz:int3 { get { return int3(w,w,z); } }
	var www:int3 { get { return int3(w,w,w); } }
	var xxxx:int4 { get { return int4(x,x,x,x); } }
	var xxxy:int4 { get { return int4(x,x,x,y); } }
	var xxxz:int4 { get { return int4(x,x,x,z); } }
	var xxxw:int4 { get { return int4(x,x,x,w); } }
	var xxyx:int4 { get { return int4(x,x,y,x); } }
	var xxyy:int4 { get { return int4(x,x,y,y); } }
	var xxyz:int4 { get { return int4(x,x,y,z); } }
	var xxyw:int4 { get { return int4(x,x,y,w); } }
	var xxzx:int4 { get { return int4(x,x,z,x); } }
	var xxzy:int4 { get { return int4(x,x,z,y); } }
	var xxzz:int4 { get { return int4(x,x,z,z); } }
	var xxzw:int4 { get { return int4(x,x,z,w); } }
	var xxwx:int4 { get { return int4(x,x,w,x); } }
	var xxwy:int4 { get { return int4(x,x,w,y); } }
	var xxwz:int4 { get { return int4(x,x,w,z); } }
	var xxww:int4 { get { return int4(x,x,w,w); } }
	var xyxx:int4 { get { return int4(x,y,x,x); } }
	var xyxy:int4 { get { return int4(x,y,x,y); } }
	var xyxz:int4 { get { return int4(x,y,x,z); } }
	var xyxw:int4 { get { return int4(x,y,x,w); } }
	var xyyx:int4 { get { return int4(x,y,y,x); } }
	var xyyy:int4 { get { return int4(x,y,y,y); } }
	var xyyz:int4 { get { return int4(x,y,y,z); } }
	var xyyw:int4 { get { return int4(x,y,y,w); } }
	var xyzx:int4 { get { return int4(x,y,z,x); } }
	var xyzy:int4 { get { return int4(x,y,z,y); } }
	var xyzz:int4 { get { return int4(x,y,z,z); } }
	//var xyzw:int4 { get { return int4(x,y,z,w); } }
	var xywx:int4 { get { return int4(x,y,w,x); } }
	var xywy:int4 { get { return int4(x,y,w,y); } }
	var xywz:int4 { get { return int4(x,y,w,z); } }
	var xyww:int4 { get { return int4(x,y,w,w); } }
	var xzxx:int4 { get { return int4(x,z,x,x); } }
	var xzxy:int4 { get { return int4(x,z,x,y); } }
	var xzxz:int4 { get { return int4(x,z,x,z); } }
	var xzxw:int4 { get { return int4(x,z,x,w); } }
	var xzyx:int4 { get { return int4(x,z,y,x); } }
	var xzyy:int4 { get { return int4(x,z,y,y); } }
	var xzyz:int4 { get { return int4(x,z,y,z); } }
	var xzyw:int4 { get { return int4(x,z,y,w); } }
	var xzzx:int4 { get { return int4(x,z,z,x); } }
	var xzzy:int4 { get { return int4(x,z,z,y); } }
	var xzzz:int4 { get { return int4(x,z,z,z); } }
	var xzzw:int4 { get { return int4(x,z,z,w); } }
	var xzwx:int4 { get { return int4(x,z,w,x); } }
	var xzwy:int4 { get { return int4(x,z,w,y); } }
	var xzwz:int4 { get { return int4(x,z,w,z); } }
	var xzww:int4 { get { return int4(x,z,w,w); } }
	var xwxx:int4 { get { return int4(x,w,x,x); } }
	var xwxy:int4 { get { return int4(x,w,x,y); } }
	var xwxz:int4 { get { return int4(x,w,x,z); } }
	var xwxw:int4 { get { return int4(x,w,x,w); } }
	var xwyx:int4 { get { return int4(x,w,y,x); } }
	var xwyy:int4 { get { return int4(x,w,y,y); } }
	var xwyz:int4 { get { return int4(x,w,y,z); } }
	var xwyw:int4 { get { return int4(x,w,y,w); } }
	var xwzx:int4 { get { return int4(x,w,z,x); } }
	var xwzy:int4 { get { return int4(x,w,z,y); } }
	var xwzz:int4 { get { return int4(x,w,z,z); } }
	var xwzw:int4 { get { return int4(x,w,z,w); } }
	var xwwx:int4 { get { return int4(x,w,w,x); } }
	var xwwy:int4 { get { return int4(x,w,w,y); } }
	var xwwz:int4 { get { return int4(x,w,w,z); } }
	var xwww:int4 { get { return int4(x,w,w,w); } }
	var yxxx:int4 { get { return int4(y,x,x,x); } }
	var yxxy:int4 { get { return int4(y,x,x,y); } }
	var yxxz:int4 { get { return int4(y,x,x,z); } }
	var yxxw:int4 { get { return int4(y,x,x,w); } }
	var yxyx:int4 { get { return int4(y,x,y,x); } }
	var yxyy:int4 { get { return int4(y,x,y,y); } }
	var yxyz:int4 { get { return int4(y,x,y,z); } }
	var yxyw:int4 { get { return int4(y,x,y,w); } }
	var yxzx:int4 { get { return int4(y,x,z,x); } }
	var yxzy:int4 { get { return int4(y,x,z,y); } }
	var yxzz:int4 { get { return int4(y,x,z,z); } }
	var yxzw:int4 { get { return int4(y,x,z,w); } }
	var yxwx:int4 { get { return int4(y,x,w,x); } }
	var yxwy:int4 { get { return int4(y,x,w,y); } }
	var yxwz:int4 { get { return int4(y,x,w,z); } }
	var yxww:int4 { get { return int4(y,x,w,w); } }
	var yyxx:int4 { get { return int4(y,y,x,x); } }
	var yyxy:int4 { get { return int4(y,y,x,y); } }
	var yyxz:int4 { get { return int4(y,y,x,z); } }
	var yyxw:int4 { get { return int4(y,y,x,w); } }
	var yyyx:int4 { get { return int4(y,y,y,x); } }
	var yyyy:int4 { get { return int4(y,y,y,y); } }
	var yyyz:int4 { get { return int4(y,y,y,z); } }
	var yyyw:int4 { get { return int4(y,y,y,w); } }
	var yyzx:int4 { get { return int4(y,y,z,x); } }
	var yyzy:int4 { get { return int4(y,y,z,y); } }
	var yyzz:int4 { get { return int4(y,y,z,z); } }
	var yyzw:int4 { get { return int4(y,y,z,w); } }
	var yywx:int4 { get { return int4(y,y,w,x); } }
	var yywy:int4 { get { return int4(y,y,w,y); } }
	var yywz:int4 { get { return int4(y,y,w,z); } }
	var yyww:int4 { get { return int4(y,y,w,w); } }
	var yzxx:int4 { get { return int4(y,z,x,x); } }
	var yzxy:int4 { get { return int4(y,z,x,y); } }
	var yzxz:int4 { get { return int4(y,z,x,z); } }
	var yzxw:int4 { get { return int4(y,z,x,w); } }
	var yzyx:int4 { get { return int4(y,z,y,x); } }
	var yzyy:int4 { get { return int4(y,z,y,y); } }
	var yzyz:int4 { get { return int4(y,z,y,z); } }
	var yzyw:int4 { get { return int4(y,z,y,w); } }
	var yzzx:int4 { get { return int4(y,z,z,x); } }
	var yzzy:int4 { get { return int4(y,z,z,y); } }
	var yzzz:int4 { get { return int4(y,z,z,z); } }
	var yzzw:int4 { get { return int4(y,z,z,w); } }
	var yzwx:int4 { get { return int4(y,z,w,x); } }
	var yzwy:int4 { get { return int4(y,z,w,y); } }
	var yzwz:int4 { get { return int4(y,z,w,z); } }
	var yzww:int4 { get { return int4(y,z,w,w); } }
	var ywxx:int4 { get { return int4(y,w,x,x); } }
	var ywxy:int4 { get { return int4(y,w,x,y); } }
	var ywxz:int4 { get { return int4(y,w,x,z); } }
	var ywxw:int4 { get { return int4(y,w,x,w); } }
	var ywyx:int4 { get { return int4(y,w,y,x); } }
	var ywyy:int4 { get { return int4(y,w,y,y); } }
	var ywyz:int4 { get { return int4(y,w,y,z); } }
	var ywyw:int4 { get { return int4(y,w,y,w); } }
	var ywzx:int4 { get { return int4(y,w,z,x); } }
	var ywzy:int4 { get { return int4(y,w,z,y); } }
	var ywzz:int4 { get { return int4(y,w,z,z); } }
	var ywzw:int4 { get { return int4(y,w,z,w); } }
	var ywwx:int4 { get { return int4(y,w,w,x); } }
	var ywwy:int4 { get { return int4(y,w,w,y); } }
	var ywwz:int4 { get { return int4(y,w,w,z); } }
	var ywww:int4 { get { return int4(y,w,w,w); } }
	var zxxx:int4 { get { return int4(z,x,x,x); } }
	var zxxy:int4 { get { return int4(z,x,x,y); } }
	var zxxz:int4 { get { return int4(z,x,x,z); } }
	var zxxw:int4 { get { return int4(z,x,x,w); } }
	var zxyx:int4 { get { return int4(z,x,y,x); } }
	var zxyy:int4 { get { return int4(z,x,y,y); } }
	var zxyz:int4 { get { return int4(z,x,y,z); } }
	var zxyw:int4 { get { return int4(z,x,y,w); } }
	var zxzx:int4 { get { return int4(z,x,z,x); } }
	var zxzy:int4 { get { return int4(z,x,z,y); } }
	var zxzz:int4 { get { return int4(z,x,z,z); } }
	var zxzw:int4 { get { return int4(z,x,z,w); } }
	var zxwx:int4 { get { return int4(z,x,w,x); } }
	var zxwy:int4 { get { return int4(z,x,w,y); } }
	var zxwz:int4 { get { return int4(z,x,w,z); } }
	var zxww:int4 { get { return int4(z,x,w,w); } }
	var zyxx:int4 { get { return int4(z,y,x,x); } }
	var zyxy:int4 { get { return int4(z,y,x,y); } }
	var zyxz:int4 { get { return int4(z,y,x,z); } }
	var zyxw:int4 { get { return int4(z,y,x,w); } }
	var zyyx:int4 { get { return int4(z,y,y,x); } }
	var zyyy:int4 { get { return int4(z,y,y,y); } }
	var zyyz:int4 { get { return int4(z,y,y,z); } }
	var zyyw:int4 { get { return int4(z,y,y,w); } }
	var zyzx:int4 { get { return int4(z,y,z,x); } }
	var zyzy:int4 { get { return int4(z,y,z,y); } }
	var zyzz:int4 { get { return int4(z,y,z,z); } }
	var zyzw:int4 { get { return int4(z,y,z,w); } }
	var zywx:int4 { get { return int4(z,y,w,x); } }
	var zywy:int4 { get { return int4(z,y,w,y); } }
	var zywz:int4 { get { return int4(z,y,w,z); } }
	var zyww:int4 { get { return int4(z,y,w,w); } }
	var zzxx:int4 { get { return int4(z,z,x,x); } }
	var zzxy:int4 { get { return int4(z,z,x,y); } }
	var zzxz:int4 { get { return int4(z,z,x,z); } }
	var zzxw:int4 { get { return int4(z,z,x,w); } }
	var zzyx:int4 { get { return int4(z,z,y,x); } }
	var zzyy:int4 { get { return int4(z,z,y,y); } }
	var zzyz:int4 { get { return int4(z,z,y,z); } }
	var zzyw:int4 { get { return int4(z,z,y,w); } }
	var zzzx:int4 { get { return int4(z,z,z,x); } }
	var zzzy:int4 { get { return int4(z,z,z,y); } }
	var zzzz:int4 { get { return int4(z,z,z,z); } }
	var zzzw:int4 { get { return int4(z,z,z,w); } }
	var zzwx:int4 { get { return int4(z,z,w,x); } }
	var zzwy:int4 { get { return int4(z,z,w,y); } }
	var zzwz:int4 { get { return int4(z,z,w,z); } }
	var zzww:int4 { get { return int4(z,z,w,w); } }
	var zwxx:int4 { get { return int4(z,w,x,x); } }
	var zwxy:int4 { get { return int4(z,w,x,y); } }
	var zwxz:int4 { get { return int4(z,w,x,z); } }
	var zwxw:int4 { get { return int4(z,w,x,w); } }
	var zwyx:int4 { get { return int4(z,w,y,x); } }
	var zwyy:int4 { get { return int4(z,w,y,y); } }
	var zwyz:int4 { get { return int4(z,w,y,z); } }
	var zwyw:int4 { get { return int4(z,w,y,w); } }
	var zwzx:int4 { get { return int4(z,w,z,x); } }
	var zwzy:int4 { get { return int4(z,w,z,y); } }
	var zwzz:int4 { get { return int4(z,w,z,z); } }
	var zwzw:int4 { get { return int4(z,w,z,w); } }
	var zwwx:int4 { get { return int4(z,w,w,x); } }
	var zwwy:int4 { get { return int4(z,w,w,y); } }
	var zwwz:int4 { get { return int4(z,w,w,z); } }
	var zwww:int4 { get { return int4(z,w,w,w); } }
	var wxxx:int4 { get { return int4(w,x,x,x); } }
	var wxxy:int4 { get { return int4(w,x,x,y); } }
	var wxxz:int4 { get { return int4(w,x,x,z); } }
	var wxxw:int4 { get { return int4(w,x,x,w); } }
	var wxyx:int4 { get { return int4(w,x,y,x); } }
	var wxyy:int4 { get { return int4(w,x,y,y); } }
	var wxyz:int4 { get { return int4(w,x,y,z); } }
	var wxyw:int4 { get { return int4(w,x,y,w); } }
	var wxzx:int4 { get { return int4(w,x,z,x); } }
	var wxzy:int4 { get { return int4(w,x,z,y); } }
	var wxzz:int4 { get { return int4(w,x,z,z); } }
	var wxzw:int4 { get { return int4(w,x,z,w); } }
	var wxwx:int4 { get { return int4(w,x,w,x); } }
	var wxwy:int4 { get { return int4(w,x,w,y); } }
	var wxwz:int4 { get { return int4(w,x,w,z); } }
	var wxww:int4 { get { return int4(w,x,w,w); } }
	var wyxx:int4 { get { return int4(w,y,x,x); } }
	var wyxy:int4 { get { return int4(w,y,x,y); } }
	var wyxz:int4 { get { return int4(w,y,x,z); } }
	var wyxw:int4 { get { return int4(w,y,x,w); } }
	var wyyx:int4 { get { return int4(w,y,y,x); } }
	var wyyy:int4 { get { return int4(w,y,y,y); } }
	var wyyz:int4 { get { return int4(w,y,y,z); } }
	var wyyw:int4 { get { return int4(w,y,y,w); } }
	var wyzx:int4 { get { return int4(w,y,z,x); } }
	var wyzy:int4 { get { return int4(w,y,z,y); } }
	var wyzz:int4 { get { return int4(w,y,z,z); } }
	var wyzw:int4 { get { return int4(w,y,z,w); } }
	var wywx:int4 { get { return int4(w,y,w,x); } }
	var wywy:int4 { get { return int4(w,y,w,y); } }
	var wywz:int4 { get { return int4(w,y,w,z); } }
	var wyww:int4 { get { return int4(w,y,w,w); } }
	var wzxx:int4 { get { return int4(w,z,x,x); } }
	var wzxy:int4 { get { return int4(w,z,x,y); } }
	var wzxz:int4 { get { return int4(w,z,x,z); } }
	var wzxw:int4 { get { return int4(w,z,x,w); } }
	var wzyx:int4 { get { return int4(w,z,y,x); } }
	var wzyy:int4 { get { return int4(w,z,y,y); } }
	var wzyz:int4 { get { return int4(w,z,y,z); } }
	var wzyw:int4 { get { return int4(w,z,y,w); } }
	var wzzx:int4 { get { return int4(w,z,z,x); } }
	var wzzy:int4 { get { return int4(w,z,z,y); } }
	var wzzz:int4 { get { return int4(w,z,z,z); } }
	var wzzw:int4 { get { return int4(w,z,z,w); } }
	var wzwx:int4 { get { return int4(w,z,w,x); } }
	var wzwy:int4 { get { return int4(w,z,w,y); } }
	var wzwz:int4 { get { return int4(w,z,w,z); } }
	var wzww:int4 { get { return int4(w,z,w,w); } }
	var wwxx:int4 { get { return int4(w,w,x,x); } }
	var wwxy:int4 { get { return int4(w,w,x,y); } }
	var wwxz:int4 { get { return int4(w,w,x,z); } }
	var wwxw:int4 { get { return int4(w,w,x,w); } }
	var wwyx:int4 { get { return int4(w,w,y,x); } }
	var wwyy:int4 { get { return int4(w,w,y,y); } }
	var wwyz:int4 { get { return int4(w,w,y,z); } }
	var wwyw:int4 { get { return int4(w,w,y,w); } }
	var wwzx:int4 { get { return int4(w,w,z,x); } }
	var wwzy:int4 { get { return int4(w,w,z,y); } }
	var wwzz:int4 { get { return int4(w,w,z,z); } }
	var wwzw:int4 { get { return int4(w,w,z,w); } }
	var wwwx:int4 { get { return int4(w,w,w,x); } }
	var wwwy:int4 { get { return int4(w,w,w,y); } }
	var wwwz:int4 { get { return int4(w,w,w,z); } }
	var wwww:int4 { get { return int4(w,w,w,w); } }
}



